In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
import ipynb.fs.full.Untitled 

import ipynb.fs.full.BACKTRACKINHG

In [ ]:
(x,y)= ipynb.fs.full.Untitled.ultimate(0,20,['NOC.mid','NOC2.mid'],1000)

In [ ]:
inp =np.array(x)
nextinp = np.array(y)

tryn=  np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])


In [ ]:
cells1=512
model = tf.keras.Sequential()

model.add(layers.LSTM(cells1,input_shape=(20,100),activation='relu'))#return_sequences=True si otra LSTM
model.add(layers.Dropout(0.3))

model.add(layers.LSTM(256,input_shape=(None,128),activation='relu'))
model.add(layers.Dense(256,activation='relu'))
model.add(layers.Dense(100,activation='sigmoid'))

In [ ]:
opt= tf.keras.optimizers.Adam(learning_rate=1e-3,decay=1e-5)


model.compile(loss='CategoricalCrossentropy',optimizer=opt,metrics=['Accuracy'])

In [ ]:
model.load_weights("model.h5")
print("Loaded model from disk")

# 

In [37]:

#WE GOT RESULTS WITH 64 LSTM -> DROPOUT 0.3 -> DENSE 100 ACTIVATION SOFTMAX = 
model = tf.keras.Sequential()
model.add(layers.LSTM(64,input_shape=(100,100),return_sequences=False))
model.add(layers.Dropout(0.3))
#model.add(layers.LSTM(16,return_sequences=True))
#model.add(layers.Dropout(0.3))
#model.add(layers.LSTM(8))
#model.add(layers.Dense(8))
#model.add(layers.Dropout(0.3))
model.add(layers.Dense(100))
model.add(layers.Activation('softmax'))
opt= tf.keras.optimizers.RMSprop(learning_rate=0.3,decay=1e-4)


model.compile(loss='CategoricalCrossentropy',optimizer=opt)
model.load_weights("modelsafestate.h5")


print("Loaded model from disk")

tryn1=  [[]]

i=0

while True: 
    i=0
    (x,y)= ipynb.fs.full.Untitled.ultimate(0,100,['1.mid','2.mid','3.mid','11.mid','12.mid','5.mid','6.mid','7.mid','8.mid','10.mid','15.mid','16.mid','17.mid','18.mid','19.mid','20.mid','21.mid','22.mid','23.mid','24.mid','25.mid','26.mid','27.mid','28.mid','29.mid','30.mid','31.mid','32.mid','33.mid','34.mid','35.mid','36.mid','37.mid','38.mid','39.mid','40.mid','41.mid','42.mid','43.mid'],2000)
    inp =np.array(x)
    nextinp = np.array(y)
    #print(inp.shape)
    tryn=  np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])
    inp=list(inp)
    inp2=[]
    nextinp=list(nextinp)
    value=True
    while value: #and #(i<(len(nextinp[1])-3)):
        
        tryn1=[]
        for j in nextinp:
            tryn1.append(j[0].copy())

        
        
        tryn=np.asarray(tryn1)
        
        #print(inp)
        
        inp=np.asarray(inp)
        #inp2=np.asarray(ipynb.fs.full.Untitled.doublestacked(inp).copy())
        #print(inp)
        #print(inp.shape)
        #WE ARE TRYING WITHOUT please conversion##actualinp=ipynb.fs.full.Untitled.please(inp)
        actualinp=np.array(inp)
        #print('O')
        #print(tryn)
        #print(actualinp.shape)
        print(actualinp.shape)
        print(tryn.shape)
        model.fit(actualinp,tryn,epochs=11)
        print(tryn)
        #print(tryn)
        inp=inp.tolist()
        val=[]
        fin=[] 
        for index,value in enumerate(inp):
            val=(inp[index][1:]).copy()
            val.append(nextinp[index][0].copy())  
            fin.append(val.copy())
        inp=fin
        
        
        for index,value in enumerate(nextinp):
            
            nextinp[index]=(nextinp[index][1:]).copy()
        
        i+=1
        for mem in nextinp:
            if (len(mem)-2)==0:
                value=False
            for lem in mem:
                if len(lem)==0:
                    value=False
                
    
    model.save_weights("model.h5")
    print("Saved model to disk")

Loaded model from disk
(38, 100, 100)
(38, 100)
Epoch 1/11


<ipython-input-37-d89caf51a0f1>:29: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nextinp = np.array(y)


2/2 [==============================] - 3s 23ms/step - loss: 156.1181
Epoch 2/11
2/2 [==============================] - 0s 24ms/step - loss: 166.6673
Epoch 3/11
2/2 [==============================] - 0s 23ms/step - loss: 167.4611
Epoch 4/11
2/2 [==============================] - 0s 22ms/step - loss: 136.9365
Epoch 5/11
2/2 [==============================] - 0s 26ms/step - loss: 124.4276
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 88.8697
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 136.8042
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 113.9149
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 163.7256
Epoch 10/11
2/2 [==============================] - 0s 25ms/step - loss: 124.1131
Epoch 11/11
2/2 [==============================] - 0s 22ms/step - loss: 139.2584
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]


2/2 [==============================] - 0s 26ms/step - loss: 69.6024
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 30ms/step - loss: 50.7352
Epoch 2/11
2/2 [==============================] - 0s 28ms/step - loss: 50.5646
Epoch 3/11
2/2 [==============================] - 0s 31ms/step - loss: 47.5885
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 40.4139
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 34.4366
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 32.5614
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 25.2495
Epoch 8/11
2/2 [==============================] - 0s 25ms/step - loss: 36.6231
Epoch 9/11
2/2 [==============================] - 0s 27ms/step - loss: 27.9205
Epoch 10/11
2/2 [=======================

2/2 [==============================] - 0s 23ms/step - loss: 37.9079
Epoch 9/11
2/2 [==============================] - 0s 25ms/step - loss: 36.3943
Epoch 10/11
2/2 [==============================] - 0s 23ms/step - loss: 35.5539
Epoch 11/11
2/2 [==============================] - 0s 24ms/step - loss: 30.2551
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 148.2807
Epoch 2/11
2/2 [==============================] - 0s 25ms/step - loss: 172.3281
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 68.6651
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 89.6862
Epoch 5/11
2/2 [==============================] - 0s 24ms/step - loss: 125.6109
Epoch 6/11
2/2 [==============================] - 0s 21ms/step - loss: 155.9019
Epoch 7/11
2/2 [==================

2/2 [==============================] - 0s 23ms/step - loss: 28.9331
Epoch 6/11
2/2 [==============================] - 0s 24ms/step - loss: 38.6257
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 26.2313
Epoch 8/11
2/2 [==============================] - 0s 26ms/step - loss: 20.8243
Epoch 9/11
2/2 [==============================] - 0s 21ms/step - loss: 19.2869
Epoch 10/11
2/2 [==============================] - 0s 22ms/step - loss: 27.7054
Epoch 11/11
2/2 [==============================] - 0s 22ms/step - loss: 24.4535
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 26ms/step - loss: 61.5840
Epoch 2/11
2/2 [==============================] - 0s 27ms/step - loss: 66.9948
Epoch 3/11
2/2 [==============================] - 0s 23ms/step - loss: 37.5759
Epoch 4/11
2/2 [======================

Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 163.5796
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 156.3717
Epoch 4/11
2/2 [==============================] - 0s 23ms/step - loss: 155.2298
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 146.1798
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 116.2194
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 134.5391
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 138.5625
Epoch 9/11
2/2 [==============================] - 0s 26ms/step - loss: 111.8606
Epoch 10/11
2/2 [==============================] - 0s 28ms/step - loss: 164.2144
Epoch 11/11
2/2 [==============================] - 0s 23ms/step - loss: 163.4992
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [=

(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 50.5311
Epoch 2/11
2/2 [==============================] - 0s 23ms/step - loss: 41.6135
Epoch 3/11
2/2 [==============================] - 0s 25ms/step - loss: 32.1727
Epoch 4/11
2/2 [==============================] - 0s 23ms/step - loss: 35.4304
Epoch 5/11
2/2 [==============================] - 0s 22ms/step - loss: 23.9975
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 28.1202
Epoch 7/11
2/2 [==============================] - 0s 25ms/step - loss: 20.2057
Epoch 8/11
2/2 [==============================] - 0s 22ms/step - loss: 23.7112
Epoch 9/11
2/2 [==============================] - 0s 26ms/step - loss: 19.9738
Epoch 10/11
2/2 [==============================] - 0s 24ms/step - loss: 18.6730
Epoch 11/11
2/2 [==============================] - 0s 24ms/step - loss: 25.6975
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]

2/2 [==============================] - 0s 25ms/step - loss: 85.5373
Epoch 11/11
2/2 [==============================] - 0s 26ms/step - loss: 113.7103
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 26ms/step - loss: 66.2758
Epoch 2/11
2/2 [==============================] - 0s 24ms/step - loss: 27.6395
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 48.7292
Epoch 4/11
2/2 [==============================] - 0s 31ms/step - loss: 35.5566
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 21.6288
Epoch 6/11
2/2 [==============================] - 0s 24ms/step - loss: 37.8793
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 34.6098
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 26.6824
Epoch 9/11
2/2 [======================

2/2 [==============================] - 0s 21ms/step - loss: 42.8318
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 37.4046
Epoch 9/11
2/2 [==============================] - 0s 23ms/step - loss: 33.0053
Epoch 10/11
2/2 [==============================] - 0s 22ms/step - loss: 41.0681
Epoch 11/11
2/2 [==============================] - 0s 29ms/step - loss: 39.7776
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 23ms/step - loss: 101.5608
Epoch 2/11
2/2 [==============================] - 0s 23ms/step - loss: 45.5509
Epoch 3/11
2/2 [==============================] - 0s 29ms/step - loss: 101.4668
Epoch 4/11
2/2 [==============================] - 0s 22ms/step - loss: 94.1132
Epoch 5/11
2/2 [==============================] - 0s 27ms/step - loss: 71.7490
Epoch 6/11
2/2 [====================

2/2 [==============================] - 0s 26ms/step - loss: 66.9338
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 37.2778
Epoch 5/11
2/2 [==============================] - 0s 22ms/step - loss: 31.7877
Epoch 6/11
2/2 [==============================] - 0s 22ms/step - loss: 59.5410
Epoch 7/11
2/2 [==============================] - 0s 25ms/step - loss: 41.0356
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 8.0760
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 50.0712
Epoch 10/11
2/2 [==============================] - 0s 21ms/step - loss: 57.8649
Epoch 11/11
2/2 [==============================] - 0s 24ms/step - loss: 19.0063
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 25ms/step - loss: 66.0324
Epoch 2/11
2/2 [=======================

(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 25ms/step - loss: 43.3191
Epoch 2/11
2/2 [==============================] - 0s 25ms/step - loss: 38.3544
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 29.1648
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 16.7956
Epoch 5/11
2/2 [==============================] - 0s 26ms/step - loss: 35.5481
Epoch 6/11
2/2 [==============================] - 0s 21ms/step - loss: 21.1007
Epoch 7/11
2/2 [==============================] - 0s 25ms/step - loss: 15.2631
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 10.5984
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 44.7390
Epoch 10/11
2/2 [==============================] - 0s 22ms/step - loss: 10.4836
Epoch 11/11
2/2 [==============================] - 0s 24ms/step - loss: 22.9249
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]

2/2 [==============================] - 0s 21ms/step - loss: 21.3619
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 76.5335
Epoch 2/11
2/2 [==============================] - 0s 36ms/step - loss: 36.5665
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 24.7152
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 20.8989
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 27.1666
Epoch 6/11
2/2 [==============================] - 0s 28ms/step - loss: 20.4256
Epoch 7/11
2/2 [==============================] - 0s 22ms/step - loss: 14.5229
Epoch 8/11
2/2 [==============================] - 0s 24ms/step - loss: 17.9549
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 16.1584
Epoch 10/11
2/2 [=======================

2/2 [==============================] - 0s 22ms/step - loss: 73.6506
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 64.6858
Epoch 10/11
2/2 [==============================] - 0s 26ms/step - loss: 90.1742
Epoch 11/11
2/2 [==============================] - 0s 22ms/step - loss: 69.5358
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 49.5826
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 35.2533
Epoch 3/11
2/2 [==============================] - 0s 23ms/step - loss: 14.6014
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 18.9707
Epoch 5/11
2/2 [==============================] - 0s 24ms/step - loss: 19.9963
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 14.7622
Epoch 7/11
2/2 [======================

2/2 [==============================] - 0s 27ms/step - loss: 28.1310
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 35.9739
Epoch 6/11
2/2 [==============================] - 0s 21ms/step - loss: 29.8059
Epoch 7/11
2/2 [==============================] - 0s 23ms/step - loss: 38.7068
Epoch 8/11
2/2 [==============================] - 0s 22ms/step - loss: 31.7912
Epoch 9/11
2/2 [==============================] - 0s 23ms/step - loss: 29.7915
Epoch 10/11
2/2 [==============================] - 0s 24ms/step - loss: 22.9212
Epoch 11/11
2/2 [==============================] - 0s 24ms/step - loss: 29.0430
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 41.0161
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 54.6037
Epoch 3/11
2/2 [======================

2/2 [==============================] - 0s 24ms/step - loss: 39.9280
Epoch 2/11
2/2 [==============================] - 0s 24ms/step - loss: 27.3945
Epoch 3/11
2/2 [==============================] - 0s 24ms/step - loss: 31.2012
Epoch 4/11
2/2 [==============================] - 0s 23ms/step - loss: 21.3378
Epoch 5/11
2/2 [==============================] - 0s 24ms/step - loss: 17.4798
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 29.4120
Epoch 7/11
2/2 [==============================] - 0s 26ms/step - loss: 37.2237
Epoch 8/11
2/2 [==============================] - 0s 25ms/step - loss: 13.0516
Epoch 9/11
2/2 [==============================] - 0s 26ms/step - loss: 14.3619
Epoch 10/11
2/2 [==============================] - 0s 27ms/step - loss: 18.7189
Epoch 11/11
2/2 [==============================] - 0s 26ms/step - loss: 15.0035
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0.

2/2 [==============================] - 0s 24ms/step - loss: 6.2832
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 65.6564
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 73.3434
Epoch 3/11
2/2 [==============================] - 0s 22ms/step - loss: 48.7640
Epoch 4/11
2/2 [==============================] - 0s 23ms/step - loss: 37.9043
Epoch 5/11
2/2 [==============================] - 0s 21ms/step - loss: 58.0515
Epoch 6/11
2/2 [==============================] - 0s 21ms/step - loss: 45.5872
Epoch 7/11
2/2 [==============================] - 0s 22ms/step - loss: 26.8066
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 30.5369
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 27.1820
Epoch 10/11
2/2 [========================

2/2 [==============================] - 0s 22ms/step - loss: 11.1010
Epoch 9/11
2/2 [==============================] - 0s 23ms/step - loss: 17.6786
Epoch 10/11
2/2 [==============================] - 0s 29ms/step - loss: 16.0616
Epoch 11/11
2/2 [==============================] - 0s 35ms/step - loss: 9.7774
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 23ms/step - loss: 106.1292
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 73.2623
Epoch 3/11
2/2 [==============================] - 0s 26ms/step - loss: 55.7031
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 60.2711
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 59.1458
Epoch 6/11
2/2 [==============================] - 0s 21ms/step - loss: 67.8562
Epoch 7/11
2/2 [======================

2/2 [==============================] - 0s 22ms/step - loss: 20.9220
Epoch 5/11
2/2 [==============================] - 0s 21ms/step - loss: 19.4763
Epoch 6/11
2/2 [==============================] - 0s 23ms/step - loss: 21.1192
Epoch 7/11
2/2 [==============================] - 0s 22ms/step - loss: 23.9248
Epoch 8/11
2/2 [==============================] - 0s 21ms/step - loss: 28.1045
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 12.7931
Epoch 10/11
2/2 [==============================] - 0s 25ms/step - loss: 22.0318
Epoch 11/11
2/2 [==============================] - 0s 21ms/step - loss: 13.5443
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 23ms/step - loss: 52.5863
Epoch 2/11
2/2 [==============================] - 0s 23ms/step - loss: 48.2045
Epoch 3/11
2/2 [======================

2/2 [==============================] - 0s 21ms/step - loss: 123.1427
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 116.6925
Epoch 3/11
2/2 [==============================] - 0s 22ms/step - loss: 132.6906
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 92.5909
Epoch 5/11
2/2 [==============================] - 0s 23ms/step - loss: 113.5457
Epoch 6/11
2/2 [==============================] - 0s 22ms/step - loss: 142.2427
Epoch 7/11
2/2 [==============================] - 0s 21ms/step - loss: 111.2648
Epoch 8/11
2/2 [==============================] - 0s 22ms/step - loss: 113.4180
Epoch 9/11
2/2 [==============================] - 0s 24ms/step - loss: 85.6589
Epoch 10/11
2/2 [==============================] - 0s 23ms/step - loss: 110.6289
Epoch 11/11
2/2 [==============================] - 0s 21ms/step - loss: 150.4105
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 

2/2 [==============================] - 0s 21ms/step - loss: 14.3492
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 22ms/step - loss: 76.0209
Epoch 2/11
2/2 [==============================] - 0s 22ms/step - loss: 31.5074
Epoch 3/11
2/2 [==============================] - 0s 22ms/step - loss: 30.8676
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 26.1883
Epoch 5/11
2/2 [==============================] - 0s 21ms/step - loss: 24.0145
Epoch 6/11
2/2 [==============================] - 0s 20ms/step - loss: 20.6596
Epoch 7/11
2/2 [==============================] - 0s 21ms/step - loss: 19.9080
Epoch 8/11
2/2 [==============================] - 0s 23ms/step - loss: 35.3168
Epoch 9/11
2/2 [==============================] - 0s 22ms/step - loss: 13.6740
Epoch 10/11
2/2 [=======================

2/2 [==============================] - 0s 33ms/step - loss: 73.5130
Epoch 9/11
2/2 [==============================] - 0s 35ms/step - loss: 91.3085
Epoch 10/11
2/2 [==============================] - 0s 30ms/step - loss: 39.5690
Epoch 11/11
2/2 [==============================] - 0s 26ms/step - loss: 48.1095
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(38, 100, 100)
(38, 100)
Epoch 1/11
2/2 [==============================] - 0s 24ms/step - loss: 58.7488
Epoch 2/11
2/2 [==============================] - 0s 27ms/step - loss: 62.3913
Epoch 3/11
2/2 [==============================] - 0s 27ms/step - loss: 33.2773
Epoch 4/11
2/2 [==============================] - 0s 24ms/step - loss: 42.0729
Epoch 5/11
2/2 [==============================] - 0s 24ms/step - loss: 62.4815
Epoch 6/11
2/2 [==============================] - 0s 32ms/step - loss: 60.3111
Epoch 7/11
2/2 [======================

KeyboardInterrupt: 

In [45]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

    
model.save_weights("modelsafe.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
print(inp)

In [46]:
mini=np.random.randint(low=0,high=200)

(rax,ray)=ipynb.fs.full.Untitled.ultimate(mini,mini+100,['43.mid'],10000)
rand=np.random.randint(low=0,high=1)
inputpred=rax



In [47]:
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = tf.keras.models.model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("modelsafe.h5")
print("Loaded model from disk")
predicted=[]
k=0
while k<2000:
    #inputpred2=np.asarray(ipynb.fs.full.Untitled.doublestacked(inputpred).copy())
    #print(inputpred2)
    
     
    #MIERDA ESTA PENSADO PARA UNA SOLA CANCION

   # CHANGE 2 actualinp2=ipynb.fs.full.Untitled.please(inputpred)
    #BEFORE CHANGES IS THIS
   # CHANGE 2 print(actualinp2)
  #  print(inputpred)
    m=loaded_model.predict(inputpred)
    res=[]
    resf=[]
  #  print(m)
   # print(m)
    
    
    
    
    
    ress=[]
    m2=np.array(m[0])
    max1=np.amax(m2)
    indexmax1=np.where(m2==np.amax(m2))
    ress.append(indexmax1)
    m2[indexmax1]=0
    indexmax1=indexmax1[0][0]
    
    #max2=np.amax(m2)
    #indexmax2=np.where(m2==np.amax(m2))
    #ress.append(indexmax2)
    #indexmax2=indexmax2[0][0]
    #indexmax2+=1
    
    zeros=[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]
    
   # print(indexmax1)
    if indexmax1!=0:
        zeros[indexmax1]=1.0
    #if indexmax2!=0:
        #indexmax2=0
        #zeros[indexmax2]=1.0
    

    
    
    
    #for i in m: 
        #res=[]
        #for j in i:
           # if j>0.8:##we could do max seems wacky but why the fuck not
               # res.append(1)
            #else:
                #res.append(0)
     #   resf.append(res.copy())
    
    
    val=[]
    fin=[] 
    for index,value in enumerate(inputpred):
        val=(inputpred[index][1:]).copy()
        #val.append(resf[index].copy())  
        val.append(zeros.copy())  
        fin.append(val.copy())
    inputpred=fin.copy()
    
    
    
    predicted.append(zeros.copy())
    k+=1

        

Loaded model from disk
1/1 [==============================] - 0s 35ms/step


1/1 [==============================] - 0s 37ms/step


1/1 [==============================] - 0s 35ms/step


1/1 [==============================] - 0s 38ms/step


1/1 [==============================] - 0s 38ms/step


1/1 [==============================] - 0s 42ms/step


1/1 [==============================] - 0s 36ms/step


1/1 [==============================] - 0s 49ms/step


1/1 [==============================] - 0s 32ms/step


1/1 [==============================] - 0s 33ms/step


1/1 [==============================] - 0s 35ms/step


1/1 [==============================] - 0s 37ms/step


1/1 [==============================] - 0s 37ms/step


In [48]:
ipynb.fs.full.BACKTRACKINHG.final(predicted,'prediction1.mid')

In [ ]:
print(predicted)